### ISSUE TITLE
Getting "PassEnv variable _ was undefined" on M1 mac

### ISSUE THREAD

**Issue by alexisig** [camptocamp/docker-qgis-server#590]
Here is my docker-compose file:

```
version: '3.7'

services:
  qgis-server:
      image: camptocamp/qgis-server:3.30
      volumes:
        - ./qgis:/etc/qgisserver
```

And here is the error I am getting:

```
AH01506: PassEnv variable _ was undefined
AH01506: PassEnv variable _ was undefined
AH00023: Couldn't create the fcgid-proctbl mutex 
```

Is the error on my side or is this project not compatible with M1 Macs? Or is it something else?

Edit: I don't have the issue with 3.26 and under.
