### ISSUE TITLE
QGIS Server: WMS does not notice changes of QGIS Project in PostGIS, but WFS does

### ISSUE THREAD

**Issue by JakobMiksch** [camptocamp/docker-qgis-server#904]
(this issue is a copy of https://github.com/qgis/QGIS/issues/56622 because I am not sure if the docker image of QGIS server itself is the problem)

### What is the bug or the crash?

When running QGIS Server with `QGIS_SERVER_PROJECT_CACHE_STRATEGY=periodic` (see [docs](QGIS_SERVER_PROJECT_CACHE_STRATEGY)), QGIS Server should react on changes of the QGIS project. This works well for WFS but **not for WMS**. 

### Steps to reproduce the issue

- start QGIS Server 3.36 with this settings (Docker compose file as example)

```
version: '3.8'
services:
  qgis_server:
    image: camptocamp/qgis-server:3.36
    volumes:
      - ./pg_service.conf:/home/.pg_service.conf
    environment:
      - QGIS_SERVER_PROJECT_CACHE_STRATEGY=periodic
      - PGSERVICEFILE=/home/.pg_service.conf
    ports:
      - "8082:80"
```

- create a QGIS project with a vector layer named `alpha` and ensure it is published both as WMS and WFS
- store this project in PostGIS
- Make a WMS and a WFS capabilities  request to the project in the database and remember the response
  - both responses should list the layer `alpha` in their response
- change the the name of the layer in your QGIS project from `alpha` to `beta`  and save the project
- Request the WMS and the WFS capabilities again. Result: 
  - WFS contains the layer called `beta` in its response
  - WMS still contains `alpha` in its response 

Do you have any idea why this behaviour appears?
